apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  resourceVersion: "384778"
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer